spring.application.name=exposicions-backend

# --- DB PRINCIPAL (app) ---
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/tfg_mvp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info

app.jwt.secret=Jo9aIvzAb1pI4QVRFd8QPDaPiKk+HGq6nKviZjDID7o=
app.jwt.expirationSeconds=86400
app.jwt.ttlDays=1

logging.level.org.springframework.security=DEBUG
logging.level.cat.cccb.tfg.exposicions.security=DEBUG

# --- DB SECUNDÀRIA (dump) - només per import ---
app.dump.datasource.url=jdbc:postgresql://127.0.0.1:5433/tfg_dump
app.dump.datasource.username=postgres
app.dump.datasource.password=postgres
app.dump.datasource.driver-class-name=org.postgresql.Driver

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

